import type { MaterialName } from './level-types'

export type TrackThemeId = 'classic' | 'industrial' | 'glacier' | 'black-gold' | 'violet' | 'pink' | 'yellow'
export type ThemeRole = 'deck' | 'accent' | 'structure' | 'alloy' | 'platform' | 'hammer' | 'handle' | 'water' | 'poolEdge'
export interface ThemeFinish { color:string; metalness:number; roughness:number; reflectivity?:number }
export interface TrackTheme { id:TrackThemeId; name:string; roles:Record<ThemeRole,ThemeFinish> }
export const trackThemes:TrackTheme[]=[
  {"id":"classic","name":"经典奶油","roles":{"deck":{"color":"#DEDBD0","metalness":0,"roughness":0.34},"accent":{"color":"#D96836","metalness":0,"roughness":0.32},"structure":{"color":"#344B50","metalness":0.18,"roughness":0.4},"alloy":{"color":"#9BAAAA","metalness":0.62,"roughness":0.3},"platform":{"color":"#729EAA","metalness":0,"roughness":0.34},"hammer":{"color":"#F1B82D","metalness":0,"roughness":0.32},"handle":{"color":"#252A2D","metalness":0,"roughness":0.58},"water":{"color":"#123C45","metalness":0,"roughness":0.32,"reflectivity":0.45},"poolEdge":{"color":"#617B80","metalness":0,"roughness":0.65}}},
  {"id":"industrial","name":"工业钢铁","roles":{"deck":{"color":"#526C88","metalness":0.4,"roughness":0.5},"accent":{"color":"#D96836","metalness":0,"roughness":0.32},"structure":{"color":"#303C47","metalness":0.35,"roughness":0.55},"alloy":{"color":"#C5D1D7","metalness":0.75,"roughness":0.3},"platform":{"color":"#789BB2","metalness":0.2,"roughness":0.42},"hammer":{"color":"#F2B635","metalness":0,"roughness":0.38},"handle":{"color":"#252A2D","metalness":0,"roughness":0.58},"water":{"color":"#101316","metalness":0,"roughness":0.34,"reflectivity":0.4},"poolEdge":{"color":"#445866","metalness":0.2,"roughness":0.55}}},
  {"id":"glacier","name":"冰蓝极境","roles":{"deck":{"color":"#69CBE0","metalness":0.03,"roughness":0.42},"accent":{"color":"#D96836","metalness":0,"roughness":0.32},"structure":{"color":"#304C63","metalness":0.2,"roughness":0.5},"alloy":{"color":"#B6D2DF","metalness":0.65,"roughness":0.28},"platform":{"color":"#3299BE","metalness":0.08,"roughness":0.38},"hammer":{"color":"#4FAECC","metalness":0,"roughness":0.38},"handle":{"color":"#252A2D","metalness":0,"roughness":0.58},"water":{"color":"#34325E","metalness":0,"roughness":0.3,"reflectivity":0.3},"poolEdge":{"color":"#55778B","metalness":0.1,"roughness":0.5}}},
  {"id":"black-gold","name":"黑金竞技","roles":{"deck":{"color":"#383F47","metalness":0.1,"roughness":0.58},"accent":{"color":"#D96836","metalness":0,"roughness":0.32},"structure":{"color":"#45413B","metalness":0.25,"roughness":0.52},"alloy":{"color":"#BFA76E","metalness":0.7,"roughness":0.32},"platform":{"color":"#53616B","metalness":0.12,"roughness":0.48},"hammer":{"color":"#D4AC53","metalness":0,"roughness":0.38},"handle":{"color":"#252A2D","metalness":0,"roughness":0.58},"water":{"color":"#C6A128","metalness":0,"roughness":0.38,"reflectivity":0.32},"poolEdge":{"color":"#8AA1A1","metalness":0.2,"roughness":0.55}}},
  {"id":"violet","name":"紫晶幻境","roles":{"deck":{"color":"#9569D4","metalness":0.05,"roughness":0.44},"accent":{"color":"#D96836","metalness":0,"roughness":0.32},"structure":{"color":"#34314D","metalness":0.2,"roughness":0.55},"alloy":{"color":"#BFC0D7","metalness":0.65,"roughness":0.32},"platform":{"color":"#684AAC","metalness":0.08,"roughness":0.44},"hammer":{"color":"#C49AED","metalness":0,"roughness":0.4},"handle":{"color":"#252A2D","metalness":0,"roughness":0.58},"water":{"color":"#492B68","metalness":0,"roughness":0.35,"reflectivity":0.3},"poolEdge":{"color":"#4E5278","metalness":0.15,"roughness":0.55}}},
  {"id":"pink","name":"樱粉乐园","roles":{"deck":{"color":"#E68DB8","metalness":0.03,"roughness":0.45},"accent":{"color":"#D96836","metalness":0,"roughness":0.32},"structure":{"color":"#423545","metalness":0.2,"roughness":0.55},"alloy":{"color":"#CEB8C5","metalness":0.65,"roughness":0.32},"platform":{"color":"#B65B91","metalness":0.08,"roughness":0.44},"hammer":{"color":"#F3B2D3","metalness":0,"roughness":0.4},"handle":{"color":"#252A2D","metalness":0,"roughness":0.58},"water":{"color":"#69344F","metalness":0,"roughness":0.35,"reflectivity":0.28},"poolEdge":{"color":"#586B73","metalness":0.15,"roughness":0.55}}},
  {"id":"yellow","name":"暖阳赛道","roles":{"deck":{"color":"#E8C64A","metalness":0.05,"roughness":0.46},"accent":{"color":"#D96836","metalness":0,"roughness":0.32},"structure":{"color":"#343E4B","metalness":0.2,"roughness":0.55},"alloy":{"color":"#B5C1CD","metalness":0.65,"roughness":0.32},"platform":{"color":"#AC8E2D","metalness":0.08,"roughness":0.44},"hammer":{"color":"#F3DB77","metalness":0,"roughness":0.4},"handle":{"color":"#252A2D","metalness":0,"roughness":0.58},"water":{"color":"#22584B","metalness":0,"roughness":0.35,"reflectivity":0.3},"poolEdge":{"color":"#4E6577","metalness":0.15,"roughness":0.55}}},
]
export function isTrackTheme(value:unknown):value is TrackThemeId { return trackThemes.some(theme=>theme.id===value) }
export function trackTheme(value:TrackThemeId) { return trackThemes.find(theme=>theme.id===value)??trackThemes[0]! }

// 保留混合警示材质及刻度/橡胶；只认语义全名，不能按RGB猜角色。
const modelRoles:Record<string,ThemeRole>={'Ivory polymer':'deck','Graphite chassis':'structure','Brushed alloy':'alloy','Platform enamel':'platform','Toy amber shell':'hammer'}
export function modelThemeRole(name:string):ThemeRole|undefined { const key=name.trim().replace(/(?:\.\d{3})+$/,'');return Object.hasOwn(modelRoles,key)?modelRoles[key]:undefined }
export const primitiveThemeRoles:Partial<Record<MaterialName,ThemeRole>>={cream:'deck',edge:'alloy',dark:'structure',blue:'platform',floorMat:'structure',water:'water',poolEdge:'poolEdge'}
export function themedPrimitiveColor(theme:TrackThemeId,key:string,classic:string) {
  const role=Object.hasOwn(primitiveThemeRoles,key)?primitiveThemeRoles[key as MaterialName]:undefined
  return theme==='classic'||!role?classic:trackTheme(theme).roles[role].color
}
